### ISSUE TITLE
create Chameleon's JDBC Driver class

### ISSUE THREAD

**Issue by NathanQingyangXu** [NathanQingyangXu/jpa-mongodb-mapping#46]
Currently we rely on the **hibernate.connection.provider_class** extension point to go about JDBC layer injection. It seems working, but it would be preferable to switch to traditional JDBC way, which requires creating a JDBC Driver class to supercede MongoConnectionProvider class.

**Comment by jyemin** [comment]
It's not clear to me where, if connection provider is removed, the MongoClient will be created and destroyed.  The MongoClient essentially acts as a connection pool, so it functions in a similar way to, say, `org.hibernate.c3p0.internal.C3P0ConnectionProvider` in hibernate-orm.  The connection provider seems like the right level of abstraction to manage the lifecycle of the MongoClient.

**Comment by NathanQingyangXu** [comment]
> It's not clear to me where, if connection provider is removed, the MongoClient will be created and destroyed. The MongoClient essentially acts as a connection pool, so it functions in a similar way to, say, `org.hibernate.c3p0.internal.C3P0ConnectionProvider` in hibernate-orm. The connection provider seems like the right level of abstraction to manage the lifecycle of the MongoClient.

Sorry, my bad. I overlooked adding the new 'MongoDriver' class to the git commit list. Now I pushed a new commit to add it.
