### ISSUE TITLE
implement CallableStatement in virtual jdbc layer

### ISSUE THREAD

**Issue by NathanQingyangXu** [NathanQingyangXu/jpa-mongodb-mapping#7]

**Comment by jyemin** [comment]
What would it call?

**Comment by NathanQingyangXu** [comment]
It would call existing mongo json function created and stored in mongo
server. Kind of simulating stored procedure in SQL.

**Comment by NathanQingyangXu** [comment]
https://www.mongodb.com/docs/manual/tutorial/store-javascript-function-on-server/

I remembered OGM does similar thing so I created this issue.

**Comment by NathanQingyangXu** [comment]
As per https://www.mongodb.com/resources/products/capabilities/stored-procedures, the stored procedure feature was provided in early MongoDB and was deprecated by MongoDB's aggregation pipeline.
For that reason, we don't need to simulate OGM to support stored procedure, I think. For that reason, I close this issue and will remove the CallableStatement implementation from our JDBC layer.
